[package]
name = "rsl"
version = "0.3.0"
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3", features = ["net", "io-util"] }
thiserror = "1.0"
url = "2.1"

[dev-dependencies]
tokio = { version = "0.3", features = ["full"] }