[package]
<<<<<<< HEAD
name = "rsl"
version = "0.4.0"
=======
>>>>>>> ca96070aa57719ac2758f97b950cab28b499f356
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"
name = "rsl"
version = "0.5.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
tokio = { version = "0.3", features = ["net", "io-util"] }
thiserror = "1.0"
url = "2.1"

[dev-dependencies]
tokio = { version = "0.3", features = ["full"] }
=======
thiserror = "1.0"
tokio = {version = "1", features = ["net", "io-util"]}
url = "2.2"

[dev-dependencies]
tokio = {version = "1", features = ["full"]}
>>>>>>> ca96070aa57719ac2758f97b950cab28b499f356
