[package]
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"
name = "rsl"
version = "0.5.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
tokio = {version = "1.5", features = ["net", "io-util"]}
url = "2.2"

[dev-dependencies]
tokio = {version = "1.5", features = ["full"]}
