[package]
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"
name = "rsl"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
percent-encoding = "2.1"
thiserror = "1.0"
tokio = {version = "1.1", features = ["net", "io-util"]}
url = "2.2"

[dev-dependencies]
tokio = {version = "1.1", features = ["full"]}
