[package]
name = "rsl"
version = "0.4.1"
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["net", "io-util"] }
thiserror = "1.0"
uri = { version = "0.3", git = "https://github.com/serbe/uri" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }