[package]
authors = ["serbe <serbenv@gmail.com>"]
edition = "2021"
name = "rsl"
version = "0.7.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
tokio = {version = "1", features = ["net", "io-util"]}
url = "2.2"

[dev-dependencies]
tokio = {version = "1", features = ["full"]}
