pub const NULL_TERMINATED: u8 = 0x00;

pub const SOCKS4_VERSION: u8 = 0x04;
pub const SOCKS4_COMMAND_TCP_CONNECT: u8 = 0x01;
pub const SOCKS4_COMMAND_TCP_BIND: u8 = 0x02;

pub const SOCKS4_REQUEST_GRANTED: u8 = 0x5A;
pub const SOCKS4_REQUEST_REJECTED_FAILED: u8 = 0x5B;
pub const SOCKS4_REQUEST_FAILED_NOT_RUNNING_IDENTD: u8 = 0x5C;
pub const SOCKS4_REQUEST_FAILED_NOT_CONFIRM_USERID: u8 = 0x5D;

pub const SOCKS5_VERSION: u8 = 0x05;
pub const SOCKS5_COMMAND_TCP_CONNECT: u8 = 0x01;
pub const SOCKS5_COMMAND_TCP_BIND: u8 = 0x02;
pub const SOCKS5_COMMAND_UDP_ASSOCIATE: u8 = 0x03;

pub const SOCKS5_ADDRESS_TYPE_IPV4: u8 = 0x01;
pub const SOCKS5_ADDRESS_TYPE_DOMAINNAME: u8 = 0x03;
pub const SOCKS5_ADDRESS_TYPE_IPV6: u8 = 0x04;

pub const SOCKS5_AUTH_NONE: u8 = 0x00;
pub const SOCKS5_AUTH_GSSAPI: u8 = 0x01;
pub const SOCKS5_AUTH_USER_PASSWORD: u8 = 0x02;
pub const SOCKS5_AUTH_NO_ACCEPT: u8 = 0xFF;

pub const SOCKS5_REPLY_SUCCESS: u8 = 0x00;
pub const SOCKS5_REPLY_GENERAL_SERVER_FAILURE: u8 = 0x01;
pub const SOCKS5_REPLY_CONNECTION_NOT_ALLOWED: u8 = 0x02;
pub const SOCKS5_REPLY_NETWORK_UNREACHABLE: u8 = 0x03;
pub const SOCKS5_REPLY_HOST_UNREACHABLE: u8 = 0x04;
pub const SOCKS5_REPLY_CONNECTION_REFUSED: u8 = 0x05;
pub const SOCKS5_REPLY_TTL_EXPIRED: u8 = 0x06;
pub const SOCKS5_REPLY_COMMAND_NOT_SUPPORTED: u8 = 0x07;
pub const SOCKS5_REPLY_ADDRESS_TYPE_NOT_SUPPORTED: u8 = 0x08;
